### ISSUE TITLE
E step

### ISSUE THREAD

**Issue by twoertwein** [belhal/saemix#1]
Hi @belhal 

I have a question about the E step of the SAEM algorithm. Unfortunately, I'm not too familiar with R - I didn't manage to get a breakpoint working inside main_estep.R

I'm using the notation from the saemix userguid. In the E step, we want to sample the individual parameters <a href="https://www.codecogs.com/eqnedit.php?latex=\psi_i" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\psi_i" title="\psi_i" /></a> from <a href="https://www.codecogs.com/eqnedit.php?latex=p(\psi_i&space;|&space;y_i,&space;\theta)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?p(\psi_i&space;|&space;y_i,&space;\theta)" title="p(\psi_i | y_i, \theta)" /></a>. If we have a constant error model (g = a), no covariates, and no transformation function h (simplifying the individual parameters to <a href="https://www.codecogs.com/eqnedit.php?latex=\psi_i&space;=&space;\mu&space;&plus;&space;\eta_i" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\psi_i&space;=&space;\mu&space;&plus;&space;\eta_i" title="\psi_i = \mu + \eta_i" /></a>):
<a href="https://www.codecogs.com/eqnedit.php?latex=\psi_i&space;=&space;\text{arg}&space;\min_{\psi_i}&space;\frac{1}{a^2}\sum_{ij}&space;||&space;f(x_{ij},&space;\psi_i)&space;-&space;y_{ij}&space;||^2&space;&plus;&space;\eta_i^T\Omega^{-1}\eta_i" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\psi_i&space;=&space;\text{arg}&space;\min_{\psi_i}&space;\frac{1}{a^2}\sum_{ij}&space;||&space;f(x_{ij},&space;\psi_i)&space;-&space;y_{ij}&space;||^2&space;&plus;&space;\eta_i^T\Omega^{-1}\eta_i" title="\psi_i = \text{arg} \min_{\psi_i} \frac{1}{a^2}\sum_{ij} || f(x_{ij}, \psi_i) - y_{ij} ||^2 + \eta_i^T\Omega^{-1}\eta_i" /></a>

Instead of sampling, I want to minimize the above equation. <a href="https://www.codecogs.com/eqnedit.php?latex=\Omega" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Omega" title="\Omega" /></a> has very quickly a (co)variance close to zero, leading to huge values in <a href="https://www.codecogs.com/eqnedit.php?latex=\Omega^{-1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Omega^{-1}" title="\Omega^{-1}" /></a>. The regularization term is order of magnitudes larger than the residual part, making it hard to minimize the above equation. I wanted to inspect how you are dealing with this issue but I'm too unfamiliar with R.

Am  missing a something in the above equation to balance the two terms? Or how do you address this issue in seamix?

Thanks,
Torsten

**Comment by BelhalK** [comment]
Hi @twoertwein,

For a breakpoint, simply put `browser()` wherever you want to stop the code running.

If you don't want to estimate your individual parameter $\psi_i$ using posterior samples but by MAP (maximum a posterior) then I believe what you are looking for is in the M-step (main_mstep.R) where maximization happens. Line 54 you will find the built-in `optim` R function that we use to optimize the fixed parameters (without random effects).

The covariance can go to zero for several reasons: 1) identifiability of the model or 2) a local trap (a local minimum to zero).
In the M-step we have implemented a simulated annealing version where those variances are multiplied by a temperature factor (line 76 to 87).

Let me know if that helps.
Bests,
Belhal

**Comment by ecomets** [comment]
On 27/03/2020 01:23, Torsten Wörtwein wrote:
> Instead of sampling, I want to minimize the above equation. [\Omega] 
> <https://www.codecogs.com/eqnedit.php?latex=\Omega> has very quickly a 
> (co)variance close to zero, leading to huge values in [\Omega^{-1}] 
> <https://www.codecogs.com/eqnedit.php?latex=\Omega^{-1}>. The regularization 
> term is order of magnitudes larger than the residual part, making it hard to 
> minimize the above equation. I wanted to inspect how you are dealing with this 
> issue but I'm too unfamiliar with R.
> 
> Am missing a something in the above equation to balance the two terms? Or how do 
> you address this issue in seamix?
> 
Hi Torsten !

I'm not sure I understand your problem.

In the SAEM algorithm as it's an EM-type algorithm, we simulate parameters in 
the E-step to obtain a complete dataset (ie we simulate the unknown parameters 
etas, within the distribution defined by omega).
What you are trying to do seems to be more like getting empirical Bayes 
estimates (ie finding "the best" individual parameters for each subject, given 
the population variability), but that's not how we use the algorithm in SAEM.
(plus your summation term is over j not ij ?)

The point is not actually to estimate those psi_i but to compute the likelihood 
of the complete data (and in SAEM we use stochastic approximation for that).

If we want to get estimates of the psi_i we do this after the estimation, by 
using conditional distributions and we take the mode or mean of that. We could 
also of course use another criteria like the one we suggest, but then naturally 
we would only consider parameters with variability (so isolating the block of 
Omega without zeros in the diagonal), and we're not too concerned about 
covariance terms, unless they become annoying in Omega-1 and then I'd probably 
go with a pseudo-inverse to minimise the criterion without numerical difficulties.

	As I said I'm not sure I got your question right so please don't hesitate to 
clarify :-)

	Best,
			Emmanuelle
-- 
Statistiquement, tout s'explique.
Personnellement, tout se complique.
         (Daniel Pennac)

**Comment by twoertwein** [comment]
thank you @belhal and @ecomets for your replies!

I'm sorry, let me try to clarify what I want to do. I want to stick as closely to SAEM as possible but to replace the sampling step of the individual parameters.

Instead of sampling at iteration k, I want to update a function with the above minimization (a and Omega are fixed) to get a better estimation of the individual parameters. The function is unlikely to reach a minimum at iteration k (the function could be learned with stochastic gradient descent). But similar to the sampling, the function will get closer and closer from iteration to iteration.

Thank you Belhal for your suggestions why Omega can be close to zero and how to deal with that!

Yes, Emmanuelle, the summation should be over j. Ignoring variables without sufficient variance sounds like a good idea!

Thanks,
Torsten

**Comment by BelhalK** [comment]
I believe that what you are suggesting is some kind of MAP-EM algorithm, where at the E-step the individual parameters $\psi_i$ are not sampled (random) but set equal as the MAP of the conditional distribution (under the current model estimate $\theta^k$.
This method shows some drawbacks and generally gets trapped in bad local minima.
Thus our desire to sample from an untractable conditional distribution and apply an accept-reject step.

Now the middle way of both methods is to obtain that MAP estimator for $\psi_i$ as the minimizer of the objective function you are proposing and to use that MAP as the mean of your proposal in the accept-reject step. As you felt it, this way the individual parameters will get closer and closer to the true value.

**Comment by ecomets** [comment]
On 27/03/2020 18:02, Belhal KARIMI wrote:
> Now the middle way of both methods is to obtain that MAP estimator for $\psi_i$ 
> as the minimizer of the objective function you are proposing and to use that MAP 
> as the mean of your proposal in the accept-reject step. As you felt it, this way 
> the individual parameters will get closer and closer to the true value.
> 
But there might be a lot of shrinkage especially with sparse data (your 
minimisation gets dominated by the Omega term and your parameters become close 
to the population parameters).
That's sort of what minimisation algorithms like FO or FOCE do and I'm not sure 
you then have the "right" likelihood to maximise...

Best,
			Emmanuelle

-- 
Statistiquement, tout s'explique.
Personnellement, tout se complique.
         (Daniel Pennac)

**Comment by twoertwein** [comment]
thank you very much again for your feedback!

One reason why the regularization term was magnitudes larger than the residual term, was that I accidentally calculated the mean fo the residual term :(

Now I observe the local minima issue @BelhalK mentioned :)
